# Generated by Django 4.2.16 on 2025-11-20 17:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('stud_id', models.CharField(blank=True, help_text='Format: ##-####-### (students) or #### (professors)', max_length=11, null=True, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('univ_email', models.EmailField(blank=True, help_text='University email must end with @cit.edu', max_length=254, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pics/')),
                ('tagline', models.CharField(blank=True, help_text='Short tagline or bio headline (e.g., "Computer Science Student | Active Contributor")', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='About me section', max_length=500, null=True)),
                ('department', models.CharField(blank=True, help_text='Academic department', max_length=100, null=True)),
                ('year_level', models.CharField(blank=True, help_text='Year level (1, 2, 3, 4, etc.)', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('is_professor', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('default_dashboard', models.CharField(choices=[('student', 'Student Dashboard'), ('overview', 'Overview'), ('resources', 'Resources'), ('quizzes', 'Quizzes')], default='student', help_text='Default dashboard view on login', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('tl', 'Tagalog')], default='en', help_text='Preferred language', max_length=5)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for updates')),
                ('notify_resource_downloads', models.BooleanField(default=True, help_text='Notify when your resources are downloaded')),
                ('notify_quiz_submissions', models.BooleanField(default=True, help_text='Notify about quiz submissions and results')),
                ('notify_system_updates', models.BooleanField(default=True, help_text='Receive system updates and announcements')),
                ('notify_weekly_summary', models.BooleanField(default=False, help_text='Receive weekly activity summary email')),
                ('in_app_sound', models.BooleanField(default=True, help_text='Enable notification sounds')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Anyone can view your profile'), ('students_only', 'Students Only - Only CIT students can view'), ('private', 'Private - Only you can view your profile')], default='students_only', help_text='Control who can view your profile', max_length=20)),
                ('deletion_requested', models.BooleanField(default=False, help_text='User has requested account deletion')),
                ('deletion_requested_at', models.DateTimeField(blank=True, help_text='When account deletion was requested', null=True)),
                ('deletion_scheduled_for', models.DateTimeField(blank=True, help_text='When account will be permanently deleted', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-trophy)', max_length=50)),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('gold', 'Gold'), ('silver', 'Silver'), ('blue', 'Blue'), ('green', 'Green')], default='purple', max_length=20)),
                ('requirement', models.CharField(help_text='How to unlock this badge', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'accounts_badge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_uploaded', models.IntegerField(default=0)),
                ('quizzes_created', models.IntegerField(default=0)),
                ('flashcards_created', models.IntegerField(default=0)),
                ('students_helped', models.IntegerField(default=0)),
                ('total_study_time', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('active_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Default', max_length=50)),
                ('font_style', models.CharField(default='System', max_length=50)),
                ('layout', models.CharField(default='Standard', max_length=50)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='StudyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email where the link was sent', max_length=254)),
                ('token', models.CharField(blank=True, help_text='Unique reset token', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expires 1 hour after creation')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'accounts_password_reset_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Device name (e.g., Chrome on Windows)', max_length=200)),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='First login time')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity time')),
                ('is_current', models.BooleanField(default=False, help_text='Current active session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_usersession',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'session_key'], name='accounts_us_user_id_150d4a_idx'), models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_upload', 'New Upload'), ('new_comment', 'New Comment'), ('new_rating', 'New Rating'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('new_bookmark', 'New Bookmark'), ('quiz_attempt', 'Quiz Attempt')], max_length=50)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, help_text='Link to related content', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (resource, quiz, flashcard, etc.)', max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'), models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('profile_complete', 'Profile Completed'), ('first_upload', 'First Upload'), ('helpful_contributor', 'Helpful Contributor'), ('quiz_creator', 'Quiz Creator'), ('streak_master', 'Streak Master'), ('top_sharer', 'Top Sharer'), ('verified_student', 'Verified Student')], max_length=50)),
                ('unlocked_date', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True, help_text='Show on profile')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'accounts_achievement',
                'ordering': ['-unlocked_date'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
