# Generated by Django 4.2.16 on 2025-10-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='stud_id',
            field=models.CharField(blank=True, help_text='Format: ##-####-### (students) or #### (professors)', max_length=11, null=True, unique=True),
        ),
    ]
