# Generated by Django 4.2.16 on 2025-11-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    # This migration previously attempted to create `PasswordResetToken`.
    # The initial migration (`0001_initial`) already defines this table in this
    # codebase. Creating it again causes duplicate-table errors on existing DBs.
    #
    # To safely mark this migration as applied without attempting to recreate
    # the table, we use a no-op RunPython. This preserves migration history
    # while avoiding duplicate creation on databases where the table already
    # exists (e.g., production or migrated instances).
    def noop(apps, schema_editor):
        return

    operations = [
        migrations.RunPython(noop, reverse_code=noop),
    ]
