# Generated by Django 4.2.16 on 2025-11-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_upload', 'New Upload'), ('new_comment', 'New Comment'), ('new_rating', 'New Rating'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('new_bookmark', 'New Bookmark'), ('quiz_attempt', 'Quiz Attempt'), ('content_review', 'Content Review Required'), ('student_question', 'Student Question'), ('new_enrollment', 'New Enrollment'), ('new_user_registration', 'New User Registration'), ('reported_content', 'Reported Content'), ('system_alert', 'System Alert'), ('password_reset_request', 'Password Reset Request')], max_length=50),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(help_text='Email or phone number provided by user', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the request')),
                ('temporary_password', models.CharField(blank=True, help_text='Temporary password generated by admin', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
