# Generated by Django 4.2.16 on 2025-11-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstats_flashcards_practiced_and_more'),
        ('accounts', '0003_alter_notification_type_passwordresetrequest'),
    ]

    operations = [
    ]
