# Generated by Django 4.2.16 on 2025-11-28 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251126_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='flashcards_practiced',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='resources_viewed',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_upload', 'New Upload'), ('new_comment', 'New Comment'), ('new_rating', 'New Rating'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('new_bookmark', 'New Bookmark'), ('quiz_attempt', 'Quiz Attempt'), ('content_review', 'Content Review Required'), ('student_question', 'Student Question'), ('new_enrollment', 'New Enrollment'), ('new_user_registration', 'New User Registration'), ('reported_content', 'Reported Content'), ('system_alert', 'System Alert'), ('password_reset_request', 'Password Reset Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_dashboard',
            field=models.CharField(choices=[('student', 'Main Dashboard'), ('overview', 'Overview'), ('resources', 'Resources'), ('quizzes', 'Quizzes')], default='student', help_text='Default dashboard view on login', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
    ]
