# Generated by Django 4.2.16 on 2025-11-28 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251126_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='flashcards_practiced',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='resources_viewed',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_upload', 'New Upload'), ('new_comment', 'New Comment'), ('new_rating', 'New Rating'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('new_bookmark', 'New Bookmark'), ('quiz_attempt', 'Quiz Attempt'), ('content_review', 'Content Review Required'), ('student_question', 'Student Question'), ('new_enrollment', 'New Enrollment'), ('new_user_registration', 'New User Registration'), ('reported_content', 'Reported Content'), ('system_alert', 'System Alert'), ('password_reset_request', 'Password Reset Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_dashboard',
            field=models.CharField(choices=[('student', 'Main Dashboard'), ('overview', 'Overview'), ('resources', 'Resources'), ('quizzes', 'Quizzes')], default='student', help_text='Default dashboard view on login', max_length=20),
        ),
        # PasswordResetToken was already created by initial migration in this
        # codebase. This duplicate CreateModel has been removed to avoid
        # duplicate-table errors on databases where the table exists.
    ]
