# Generated by Django 4.2.7 on 2025-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='code',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(blank=True, help_text='Unique reset token', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='email',
            field=models.EmailField(help_text='Email where the link was sent', max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Token expires 1 hour after creation'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether the token has been used'),
        ),
    ]
