# Generated by Django 4.2.16 on 2025-12-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userstats_flashcards_practiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.EmailField(blank=True, help_text='Optional backup email for account recovery', max_length=254, null=True),
        ),
    ]
