# Generated by Django 4.2.7 on 2025-10-30 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_passwordresettoken_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-trophy)', max_length=50)),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('gold', 'Gold'), ('silver', 'Silver'), ('blue', 'Blue'), ('green', 'Green')], default='purple', max_length=20)),
                ('requirement', models.CharField(help_text='How to unlock this badge', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'accounts_badge',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='About me section', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Academic department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline or bio headline (e.g., "Computer Science Student | Active Contributor")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, help_text='Year level (1, 2, 3, 4, etc.)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('profile_complete', 'Profile Completed'), ('first_upload', 'First Upload'), ('helpful_contributor', 'Helpful Contributor'), ('quiz_creator', 'Quiz Creator'), ('streak_master', 'Streak Master'), ('top_sharer', 'Top Sharer'), ('verified_student', 'Verified Student')], max_length=50)),
                ('unlocked_date', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True, help_text='Show on profile')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'accounts_achievement',
                'ordering': ['-unlocked_date'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
