# Generated by Django 5.2.7 on 2025-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSCE', 'Bachelor of Science in Computer Engineering'), ('BSIS', 'Bachelor of Science in Information Systems'), ('ACT', 'Associate in Computer Technology')], help_text='Academic course/program', max_length=10, null=True),
        ),
    ]
