# Generated by Django 4.2.7 on 2025-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_badge_user_bio_user_department_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_dashboard',
            field=models.CharField(choices=[('student', 'Student Dashboard'), ('overview', 'Overview'), ('resources', 'Resources'), ('flashcards', 'Flashcards'), ('quizzes', 'Quizzes')], default='student', help_text='Default dashboard view on login', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('tl', 'Tagalog')], default='en', help_text='Preferred language', max_length=5),
        ),
    ]
