# Generated by Django 4.2.7 on 2025-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_default_dashboard_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for updates'),
        ),
        migrations.AddField(
            model_name='user',
            name='in_app_sound',
            field=models.BooleanField(default=True, help_text='Enable notification sounds'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_quiz_submissions',
            field=models.BooleanField(default=True, help_text='Notify about quiz submissions and results'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_resource_downloads',
            field=models.BooleanField(default=True, help_text='Notify when your resources are downloaded'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_system_updates',
            field=models.BooleanField(default=True, help_text='Receive system updates and announcements'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_weekly_summary',
            field=models.BooleanField(default=False, help_text='Receive weekly activity summary email'),
        ),
    ]
