# Generated by Django 4.2.7 on 2025-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_notifications_user_in_app_sound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can view your profile'), ('students_only', 'Students Only - Only CIT students can view'), ('private', 'Private - Only you can view your profile')], default='students_only', help_text='Control who can view your profile', max_length=20),
        ),
    ]
