# Generated by Django 4.2.7 on 2025-10-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_profile_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Device name (e.g., Chrome on Windows)', max_length=200)),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device')),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='First login time')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity time')),
                ('is_current', models.BooleanField(default=False, help_text='Current active session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_usersession',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'session_key'], name='accounts_us_user_id_150d4a_idx'), models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx')],
            },
        ),
    ]
