# Generated by Django 4.2.7 on 2025-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested',
            field=models.BooleanField(default=False, help_text='User has requested account deletion'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When account deletion was requested', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When account will be permanently deleted', null=True),
        ),
    ]
