# Generated by Django 4.2.7 on 2025-11-17 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studyreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_dashboard',
            field=models.CharField(choices=[('student', 'Student Dashboard'), ('overview', 'Overview'), ('resources', 'Resources'), ('quizzes', 'Quizzes')], default='student', help_text='Default dashboard view on login', max_length=20),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_uploaded', models.IntegerField(default=0)),
                ('quizzes_created', models.IntegerField(default=0)),
                ('flashcards_created', models.IntegerField(default=0)),
                ('students_helped', models.IntegerField(default=0)),
                ('total_study_time', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('active_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Default', max_length=50)),
                ('font_style', models.CharField(default='System', max_length=50)),
                ('layout', models.CharField(default='Standard', max_length=50)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
