# Generated by Django 4.2.16 on 2025-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_deckcomment_deckrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10),
        ),
    ]
