# Generated by Django 4.2.16 on 2025-11-16 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0006_deck_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='verification_by',
            field=models.ForeignKey(blank=True, help_text='Professor/staff user who verified this deck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deck',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when deck was verified', null=True),
        ),
    ]
