# Generated by Django 4.2.16 on 2025-11-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0007_deck_verification_by_deck_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deckcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='deckcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='flashcards.deckcomment'),
        ),
        migrations.AddIndex(
            model_name='deckcomment',
            index=models.Index(fields=['deck', 'created_at'], name='flashcards__deck_id_b94f8b_idx'),
        ),
        migrations.AddField(
            model_name='decklike',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='flashcards.deck'),
        ),
        migrations.AddField(
            model_name='decklike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='decklike',
            index=models.Index(fields=['deck', 'created_at'], name='flashcards__deck_id_f4f719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decklike',
            unique_together={('user', 'deck')},
        ),
    ]
