# Generated by Django 4.2.16 on 2025-11-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0008_decklike_alter_deckcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='is_bookmarked',
        ),
        migrations.CreateModel(
            name='DeckBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='flashcards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deck', 'created_at'], name='flashcards__deck_id_ee88ce_idx')],
                'unique_together': {('user', 'deck')},
            },
        ),
    ]
