# Generated by Django 4.2.16 on 2025-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_merge_0002_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizbookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
