# Generated by Django 4.2.16 on 2025-11-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0005_quizcomment_quizrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='quizcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quizzes.quizcomment'),
        ),
        migrations.AddIndex(
            model_name='quizcomment',
            index=models.Index(fields=['quiz', 'created_at'], name='quizzes_qui_quiz_id_f0b5ea_idx'),
        ),
        migrations.AddField(
            model_name='quizlike',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quizlike',
            index=models.Index(fields=['quiz', 'created_at'], name='quizzes_qui_quiz_id_7fb0fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizlike',
            unique_together={('user', 'quiz')},
        ),
    ]
