# Generated by Django 4.2.7 on 2025-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, visible to all users. If False, only visible to uploader.'),
        ),
    ]
