# Generated by Django 4.2.16 on 2025-11-24 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0004_resource_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resources.comment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['resource', 'created_at'], name='resources_c_resourc_312762_idx'),
        ),
        migrations.AddField(
            model_name='like',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['resource', 'created_at'], name='resources_l_resourc_f1080f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'resource')},
        ),
    ]
